### ISSUE TITLE
windows build issue started with MSVC 17.14.x

### ISSUE THREAD

**Issue by toloudis** [google/tensorstore#242]
I started getting this build error on Windows with my code that includes tensorstore.h.
It started happening in my CI just after github updated the windows-2022 runner to 17.14 from 17.13.   This also happened on my windows workstation when I updated visual studio to 17.14.
Does any of this look familiar or ring a bell?  
The ai copilots offer local changes to `intrusive_ptr` 's sfinae checks which make it compile again. 

```
2025-07-18T23:21:24.5383279Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/internal/intrusive_ptr.h(360): error C2938: 'std::enable_if_t<false,void>' : Failed to specialize alias template
2025-07-18T23:21:24.5693465Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/internal/intrusive_ptr.h(360): note: the template instantiation context (the oldest one first) is
2025-07-18T23:21:24.7414432Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/context_impl_base.h(372): note: while compiling class template 'tensorstore::internal_context::ResourceProviderImpl'
2025-07-18T23:21:24.7724911Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/context_impl_base.h(399): note: while compiling class 'tensorstore::internal_context::ResourceProviderImpl<Traits>::SpecImpl'
2025-07-18T23:21:24.9444474Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/context_impl_base.h(404): note: see reference to class template instantiation 'tensorstore::Result<tensorstore::internal_context::ResourceImplStrongPtr>' being compiled
2025-07-18T23:21:24.9759424Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/util/result.h(138): note: see reference to class template instantiation 'tensorstore::internal_result::ResultStorage<T>' being compiled
2025-07-18T23:21:25.1474900Z         with
2025-07-18T23:21:25.3510619Z         [
2025-07-18T23:21:25.5391557Z             T=tensorstore::internal_context::ResourceImplStrongPtr
2025-07-18T23:21:25.7429241Z         ]
2025-07-18T23:21:25.9467870Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/util/result_impl.h(155): note: see reference to class template instantiation 'tensorstore::internal::IntrusivePtr<tensorstore::internal_context::ResourceImplBase,tensorstore::internal_context::ResourceImplStrongPtrTraits>' being compiled
2025-07-18T23:21:26.1498009Z D:\a\agave\agave\build\_deps\tensorstore-src\tensorstore/internal/intrusive_ptr.h(360): note: see reference to alias template instantiation 'std::enable_if_t<false,void>' being compiled
```

**Comment by laramiel** [comment]
Interesting. What are the local edits which you applied to get it to build?
