### ISSUE TITLE
Build breaks on arm64 due to apparent arch name change

### ISSUE THREAD

**Issue by yhtang** [google/tensorstore#77]
Hi there,

We have a nightly pipeline and it started to fail since two days ago when `pip install tensorstore` due to the following error:
```
#25 7.342 Building wheels for collected packages: tensorstore
#25 7.342   Building wheel for tensorstore (pyproject.toml): started
#25 7.607   Building wheel for tensorstore (pyproject.toml): finished with status 'error'
#25 7.617   error: subprocess-exited-with-error
#25 7.617   
#25 7.617   × Building wheel for tensorstore (pyproject.toml) did not run successfully.
#25 7.617   │ exit code: 1
#25 7.617   ╰─> [21 lines of output]
#25 7.617       running bdist_wheel
#25 7.617       running build
#25 7.617       running build_py
#25 7.617       creating /tmp/tmpjmd4_3gr/lib.linux-aarch64-cpython-310
#25 7.617       creating /tmp/tmpjmd4_3gr/lib.linux-aarch64-cpython-310/tensorstore
#25 7.617       copying python/tensorstore/__init__.py -> /tmp/tmpjmd4_3gr/lib.linux-aarch64-cpython-310/tensorstore
#25 7.617       running build_ext
#25 7.617       /usr/local/bin/python3.10 -u bazelisk.py build -c opt //python/tensorstore:_tensorstore__shared_objects --verbose_failures --copt=-fvisibility=hidden
#25 7.617       Traceback (most recent call last):
#25 7.617         File "/tmp/pip-install-2223fhi8/tensorstore_f6ce3519ee494f2484aa855286d70b8a/bazelisk.py", line 490, in <module>
#25 7.617           sys.exit(main())
#25 7.617         File "/tmp/pip-install-2223fhi8/tensorstore_f6ce3519ee494f2484aa855286d70b8a/bazelisk.py", line 475, in main
#25 7.617           bazel_path = get_bazel_path()
#25 7.617         File "/tmp/pip-install-2223fhi8/tensorstore_f6ce3519ee494f2484aa855286d70b8a/bazelisk.py", line 468, in get_bazel_path
#25 7.617           return download_bazel_into_directory(bazel_version, is_commit, bazel_directory)
#25 7.617         File "/tmp/pip-install-2223fhi8/tensorstore_f6ce3519ee494f2484aa855286d70b8a/bazelisk.py", line 292, in download_bazel_into_directory
#25 7.617           bazel_filename = determine_bazel_filename(version)
#25 7.617         File "/tmp/pip-install-2223fhi8/tensorstore_f6ce3519ee494f2484aa855286d70b8a/bazelisk.py", line 219, in determine_bazel_filename
#25 7.617           raise Exception(
#25 7.617       Exception: Unsupported machine architecture "aarch64". Bazel 5.4.0 only supports x86_64, arm64 on Linux.
```

Should `aarch64` and `arm64` be treated as the same here?

**Comment by laramiel** [comment]
Yes, bazel uses arm64 for here.

**Comment by yhtang** [comment]
> were you previously testing in a different configuration?

The configuration, in principle, should be the same, although given that it is a nightly container build so we might be pulling in differences via the base image or the system package manager.

**Comment by laramiel** [comment]
What does this output on your image:

```
python -c 'import platform; print(platform.machine())'
```

**Comment by yhtang** [comment]
> What does this output on your image:

I was just gonna post a repro, here here it is 😄:

```
$ uname -a
Linux 5.13.0-48-generic #54~20.04.1-Ubuntu SMP Thu Jun 2 23:38:52 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$ python -c 'import platform; print(platform.machine())'
aarch64
```
The docker command:
```
$ docker run -it ubuntu:20.04 bash
```
Trying to install tensorstore:
```
# apt-get update && apt-get install -y python3-pip
...
# python3 --version
Python 3.8.10
# pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
# pip install tensorstore
Collecting tensorstore
  Downloading tensorstore-0.1.31.tar.gz (5.3 MB)
     |████████████████████████████████| 5.3 MB 6.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting numpy>=1.16.0
  Downloading numpy-1.24.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 48.4 MB/s 
Building wheels for collected packages: tensorstore
  Building wheel for tensorstore (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmppuf6j6_w build_wheel /tmp/tmpfo8kg47l
       cwd: /tmp/pip-install-sp1m9x47/tensorstore
  Complete output (21 lines):
  running bdist_wheel
  running build
  running build_py
  creating /tmp/tmprawnubsl/lib.linux-aarch64-cpython-38
  creating /tmp/tmprawnubsl/lib.linux-aarch64-cpython-38/tensorstore
  copying python/tensorstore/__init__.py -> /tmp/tmprawnubsl/lib.linux-aarch64-cpython-38/tensorstore
  running build_ext
  /usr/bin/python3 -u bazelisk.py build -c opt //python/tensorstore:_tensorstore__shared_objects --verbose_failures --copt=-fvisibility=hidden
  Traceback (most recent call last):
    File "bazelisk.py", line 490, in <module>
      sys.exit(main())
    File "bazelisk.py", line 475, in main
      bazel_path = get_bazel_path()
    File "bazelisk.py", line 468, in get_bazel_path
      return download_bazel_into_directory(bazel_version, is_commit, bazel_directory)
    File "bazelisk.py", line 292, in download_bazel_into_directory
      bazel_filename = determine_bazel_filename(version)
    File "bazelisk.py", line 219, in determine_bazel_filename
      raise Exception(
  Exception: Unsupported machine architecture "aarch64". Bazel 5.4.0 only supports x86_64, arm64 on Linux.
  error: command '/usr/bin/python3' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for tensorstore
Failed to build tensorstore
ERROR: Could not build wheels for tensorstore which use PEP 517 and cannot be installed directly
```

**Comment by laramiel** [comment]
That makes me think that bazelisk should adjust the arch.

https://github.com/bazelbuild/bazelisk/blob/990c873143eca3210f004b80a326dbab9856279a/bazelisk.py#L257

If that normalized 'aarch64' -> 'arm64' it might work.

**Comment by yhtang** [comment]
I agree that this is indeed a Bazelisk issue. I'll post an issue there then.

**Comment by jbms** [comment]
Yes, it looks like it should be fixed in bazelisk. But it is still very confusing that it worked previously --- that suggests that previously `uname` was returning `arm64` for you.

**Comment by yhtang** [comment]
> But it is still very confusing that it worked previously --- that suggests that previously uname was returning arm64 for you.

I'm wondering the same and still looking to see what exactly has changed.

**Comment by jbms** [comment]
This is the same issue as https://github.com/google/tensorstore/issues/35

In fact even after fixing this bazelisk issue there are a couple other issues that still need to be fixed in order for the Linux arm64 build to work.  Hopefully we will have them fixed soon.

But given these issues, it seems that most likely you were *not* previously building on linux arm64.

**Comment by yhtang** [comment]
> But given these issues, it seems that most likely you were not previously building on linux arm64.

I just find out the reason --- a new package was added 3 days ago that depend on tensorstore. Prior to that it was not installed at all in the ARM build! 🤣

**Comment by laramiel** [comment]
Ok, with the submitted changes I think that head will build with arm64. 
  
If you're on a local machine and want to try it, you may need prerequisites:

```
sudo apt-get install -y \
      build-essential \
      gcc \
      g++ \
      git \
      unzip \
      wget \
      python3 \
      python3-dev \
      python3-pip

sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
python3 -m pip install --upgrade pip setuptools
```

Then you should be able to follow the instructions here:

*  https://google.github.io/tensorstore/installation.html#installation-from-local-checkout

**Comment by yhtang** [comment]
The good news is that I can now get into the build step of the installation.
The bad news is that the compilation failed: https://gist.github.com/yhtang/555d8e70190624ea7e2d2e96dada0199.
😁

**Comment by jbms** [comment]
Can you say which compiler version and/or container image you are using?

GCC 10 or later is required.

We hope to set up building of binary wheel packages for Linux arm64 which would avoid the need for all users to build the package themselves, but that will take some time to set up.

**Comment by yhtang** [comment]
That was a vanilla ubuntu 20.04 image (`docker pull ubuntu:20.04`), so the GCC that comes with it is, unfortunately, 9.4.0. 
After changing to ubuntu 22.04, I can now build tensorstore. 🍾  

Just for information purposes, is there a timeline for tensorstore to have an official ARM build?

**Comment by laramiel** [comment]
I'm working now on our CI for arm64, so that should, at least, ensure that we have a consistently working ARM64 build. We're looking at options for an official pypi arm64 build.

**Comment by laramiel** [comment]
We have a CI running for arm64 which should detect if the build break reoccurs.

**Comment by nouiz** [comment]
Great news.
Any idea when a release will be done to be able to install it easily on arm64?

**Comment by laramiel** [comment]
It should work with versions >= [v0.1.33](https://github.com/google/tensorstore/tree/v0.1.33).  Certainly the latest [v0.1.35](https://github.com/google/tensorstore/tree/v0.1.35) should have no issues building on arm64.
